# Generated by Django 3.2.4 on 2021-06-27 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AOSR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_number_prefix', models.CharField(blank=True, max_length=20, verbose_name='Префикс номера акта')),
                ('act_number', models.CharField(blank=True, max_length=20, verbose_name='Номер акта')),
                ('act_date', models.CharField(max_length=50, verbose_name='Дата Акта')),
                ('presented_work', models.CharField(max_length=500, verbose_name='Предъявл.')),
                ('materials', models.CharField(max_length=500, verbose_name='Материалы')),
                ('permitted_work', models.CharField(max_length=500, verbose_name='Разрешено')),
                ('begin_date', models.CharField(max_length=50, verbose_name='От:')),
                ('end_date', models.CharField(max_length=50, verbose_name='До:')),
                ('work_SNIP', models.CharField(blank=True, max_length=500, verbose_name='СНИП:')),
                ('docs', models.CharField(blank=True, default='исполнительная схема, сертификаты/свителельства', max_length=500, verbose_name='Предьявлены документы')),
                ('annex', models.CharField(blank=True, max_length=500, verbose_name='Приложения')),
            ],
            options={
                'verbose_name': 'Акт скрытых',
                'verbose_name_plural': 'Акты скрытых',
            },
        ),
        migrations.CreateModel(
            name='ObjectActs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('work', models.CharField(max_length=500, verbose_name='Работа')),
                ('client', models.CharField(max_length=500, verbose_name='Заказчик с реквизитами')),
                ('designer', models.CharField(max_length=500, verbose_name='Проектант с реквизитами')),
                ('contractor', models.CharField(max_length=500, verbose_name='Подрядчик с реквизитами')),
                ('supervisor_engineer', models.CharField(max_length=200, verbose_name='Технадзор')),
                ('contractor_engineer', models.CharField(max_length=200, verbose_name='Прораб')),
                ('designer_engineer', models.CharField(blank=True, max_length=200, verbose_name='Проектировщик')),
                ('project_number', models.CharField(max_length=100, verbose_name='Ном. проекта')),
                ('exec_documents', models.CharField(max_length=500, verbose_name='Исполн.')),
                ('supervisor_engineer_decree', models.CharField(max_length=200, verbose_name='Приказ технадзора')),
                ('contractor_engineer_decree', models.CharField(max_length=200, verbose_name='Приказ прораба')),
                ('designer_engineer_decree', models.CharField(blank=True, max_length=200, verbose_name='Приказ проектировщика')),
                ('acts_instance_num', models.CharField(blank=True, max_length=100, verbose_name='Кол-во экземпляров')),
            ],
            options={
                'verbose_name': 'Набор актов объекта ',
                'verbose_name_plural': 'Наборы актов объекта',
            },
        ),
        migrations.CreateModel(
            name='AOSRFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='media/%Y/%m/%d/', verbose_name='Файл к акту')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('corner_text', models.CharField(blank=True, max_length=255, verbose_name='Текст в углу')),
                ('aosr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='aosr.aosr', verbose_name='файлы')),
            ],
            options={
                'verbose_name': 'Файл к АОСР',
                'verbose_name_plural': 'Файлы для АОСР',
            },
        ),
        migrations.AddField(
            model_name='aosr',
            name='object_acts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aosr_set', to='aosr.objectacts', verbose_name='Набор актов объекта'),
        ),
    ]
